'use client';

import { useEffect, useMemo, useState } from 'react';
import { Bell, ChevronRight, MessageCircle, Plus, Search, Settings, Users, UserRound, X } from 'lucide-react';
import { Avatar } from './Avatar';
import { MapPanel } from './MapPanel';
import { PscMicrosoftAuthButton } from './PscMicrosoftAuthButton';
import { avatarDefaults } from '@/lib/data';
import type { AvatarConfig, DataMode, Lesson, Person } from '@/lib/types';
import { supabaseBrowser } from '@/lib/supabase';
import { createGroup, follow, getDirectMessages, getGroups, getTimetable, loadPeople, sendDirectMessage, setLocation, unfollow, updateProfile } from '@/lib/live';
import type { SupabaseClient, User } from '@supabase/supabase-js';

function connectionScore() { if (typeof navigator === 'undefined') return 1; const c = (navigator as Navigator & { connection?: { effectiveType?: string; rtt?: number; saveData?: boolean } }).connection; if (!c) return 1; if (c.saveData) return .2; if (c.effectiveType === 'slow-2g' || c.effectiveType === '2g') return .15; if (c.effectiveType === '3g') return .55; if ((c.rtt ?? 0) > 800) return .3; if ((c.rtt ?? 0) > 450) return .55; return 1; }
function useDataMode() { const [mode, setMode] = useState<DataMode>('full'); const [ultra, setUltra] = useState(false); useEffect(() => { const update = () => { const s = connectionScore(); setMode(s < .25 && ultra ? 'ultra' : s < .65 ? 'low' : 'full'); }; update(); const id = window.setInterval(update, 8000); return () => window.clearInterval(id); }, [ultra]); return { mode, ultra, setUltra }; }
function registerSW() { if (typeof window !== 'undefined' && 'serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {}); }
function useLocalState<T>(key: string, initial: T) { const [value, setValue] = useState<T>(initial); useEffect(() => { try { const raw = localStorage.getItem(key); if (raw) setValue(JSON.parse(raw)); } catch {} }, [key]); useEffect(() => { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} }, [key, value]); return [value, setValue] as const; }
function toMinutes(value: string) { const [h, m] = value.slice(0, 5).split(':').map(Number); return h * 60 + m; }
function greeting() { const h = new Date().getHours(); return h < 12 ? 'Good morning' : h < 18 ? 'Good afternoon' : 'Good evening'; }
type LivePerson = Person & { mutual: boolean; following: boolean; follower: boolean; exact: boolean };

export function BluoApp() {
 const [sb] = useState<SupabaseClient | null>(() => supabaseBrowser());
 const [sessionUser, setSessionUser] = useState<User | null>(null); const [loading, setLoading] = useState(Boolean(sb));
 const [name, setName] = useLocalState('bluo-name', ''); const [email, setEmail] = useLocalState('bluo-email', ''); const [yearGroup, setYearGroup] = useLocalState('bluo-year', 2028); const [profile, setProfile] = useLocalState<AvatarConfig>('bluo-avatar', avatarDefaults);
 const [tab, setTab] = useState<'home' | 'friends' | 'chat' | 'groups' | 'profile'>('home'); const [filter, setFilter] = useState<'friends' | 'nearby' | 'everyone'>('friends'); const [sheet, setSheet] = useState<'settings' | 'avatar' | 'timetable' | 'notifications' | null>(null); const [people, setPeople] = useState<LivePerson[]>([]); const [lessons, setLessons] = useState<Lesson[]>([]); const [myLocation, setMyLocation] = useState<[number, number] | undefined>(); const [error, setError] = useState(''); const { mode, ultra, setUltra } = useDataMode(); useEffect(registerSW, []);
 useEffect(() => { if (!sb) { setLoading(false); return; } let alive = true; void sb.auth.getUser().then(({ data, error: authError }) => { if (!alive) return; if (authError) setError(authError.message); setSessionUser(data.user); setLoading(false); }); const { data: listener } = sb.auth.onAuthStateChange((_event, session) => { if (alive) setSessionUser(session?.user ?? null); }); return () => { alive = false; listener.subscription.unsubscribe(); }; }, [sb]);
 useEffect(() => { if (!sb || !sessionUser) return; let cancelled = false; const refresh = async () => { try { const { data, error: pError } = await sb.from('profiles').select('display_name,avatar,year_group').eq('id', sessionUser.id).single(); if (pError) throw pError; let displayName = data.display_name; let nextYear = data.year_group; const pendingRaw = typeof window !== 'undefined' ? localStorage.getItem('bluo-pending-profile') : null; if (pendingRaw) { try { const pending = JSON.parse(pendingRaw) as { name?: string; yearGroup?: number }; if (typeof pending.name === 'string' && pending.name.trim() && typeof pending.yearGroup === 'number' && Number.isInteger(pending.yearGroup) && pending.yearGroup >= 2027 && pending.yearGroup <= 2040) { await updateProfile(sb, sessionUser.id, { display_name: pending.name.trim(), year_group: pending.yearGroup }); displayName = pending.name.trim(); nextYear = pending.yearGroup; localStorage.removeItem('bluo-pending-profile'); } } catch {} } const [nextPeople, nextLessons] = await Promise.all([loadPeople(sb, sessionUser.id, myLocation), getTimetable(sb, sessionUser.id)]); if (cancelled) return; setName(displayName); setProfile(data.avatar || avatarDefaults); if (nextYear) setYearGroup(nextYear); const mapped = nextLessons.map(l => ({ day: l.day, start: l.start_time.slice(0, 5), end: l.end_time.slice(0, 5), name: l.subject, room: l.room ?? undefined })); setPeople(nextPeople); setLessons(mapped); } catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : 'Could not load your Bluo data.'); } }; void refresh(); return () => { cancelled = true; }; }, [sb, sessionUser, myLocation, setName, setProfile, setYearGroup]);
 useEffect(() => { if (!sb || !sessionUser || typeof navigator === 'undefined' || !navigator.geolocation) return; let active = true; const send = () => navigator.geolocation.getCurrentPosition(async p => { if (!active) return; setMyLocation([p.coords.latitude, p.coords.longitude]); try { await setLocation(sb, p.coords); } catch {} }, () => {}, { enableHighAccuracy: false, maximumAge: 180000, timeout: 10000 }); send(); const id = window.setInterval(send, 300000); return () => { active = false; window.clearInterval(id); }; }, [sb, sessionUser]);
 const visiblePeople = useMemo(() => filter === 'friends' ? people.filter(p => p.mutual) : filter === 'nearby' ? people.slice(0, 10) : people, [filter, people]); const freePeople = people.filter(p => p.free);
 if (!sb) return <main className="onboarding"><div className="onboarding-card"><div className="logo">Bluo<span className="logo-dot" /></div><h1>Bluo is not configured</h1><p>The production app could not connect to its backend. Please try again shortly.</p></div></main>;
 if (loading) return <main className="onboarding"><div className="onboarding-card"><div className="logo">Bluo<span className="logo-dot" /></div><h1>Loading Bluo…</h1><p>Checking your secure session.</p></div></main>;
 if (!sessionUser) return <Onboarding sb={sb} name={name} setName={setName} email={email} setEmail={setEmail} yearGroup={yearGroup} setYearGroup={setYearGroup} error={error} onEnter={async ({ password, mode }) => { setError(''); try { if (mode === 'signup') throw new Error('New accounts use your PSC Microsoft account.'); const clean = email.trim().toLowerCase(); if (!clean.endsWith('@students.psc.ac.uk')) throw new Error('Use your @students.psc.ac.uk email.'); if (password.length < 8) throw new Error('Password must be at least 8 characters.'); const { error: e } = await sb.auth.signInWithPassword({ email: clean, password }); if (e) throw e; return true; } catch (e) { setError(e instanceof Error ? e.message : 'Could not complete authentication.'); return false; } }} />;
 return <div className="app-shell"><header className="topbar"><div className="brand"><div className="logo">Bluo<span className="logo-dot" /></div></div><div className="top-actions"><button className="icon-btn" onClick={() => setSheet('notifications')} aria-label="Notifications"><Bell size={18} /></button><button className="avatar-btn" onClick={() => setTab('profile')} aria-label="Profile"><Avatar config={profile} size={43} /></button></div></header><main className="main">
 {tab === 'home' && <><div className="hero-row"><div><div className="eyebrow">Peter Symonds College · Graduation {yearGroup}</div><h1 className="hero-title">{greeting()}, {name} <span>👋</span></h1></div><div className="mode-pill"><span className="mode-dot" /><span>{mode === 'full' ? 'Full data' : mode === 'low' ? 'Low data' : 'Ultra low data'}</span></div></div><div className="grid"><MapPanel people={visiblePeople} filter={filter} onFilter={setFilter} /><div className="side"><section className="card side-card"><div className="card-head"><div className="card-title">Free right now</div><button className="text-btn" onClick={() => setTab('friends')}>See all</button></div>{freePeople.length ? freePeople.slice(0, 4).map(p => <PersonRow key={p.id} p={p} onAction={() => setTab('chat')} />) : <p className="person-meta">Your friends' availability will appear here once they join and add a timetable.</p>}</section><section className="card side-card"><div className="card-head"><div className="card-title">Your next free</div><button className="text-btn" onClick={() => setSheet('timetable')}>Timetable</button></div><TimetableSummary lessons={lessons} /></section></div></div></>}
 {tab === 'friends' && <Friends people={people} onFollow={async p => { if (!sb || !sessionUser) return; try { if (p.following) await unfollow(sb, sessionUser.id, p.id); else await follow(sb, sessionUser.id, p.id); setPeople(await loadPeople(sb, sessionUser.id, myLocation)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update connection.'); } }} />}
 {tab === 'chat' && <Chat people={people} sb={sb} userId={sessionUser.id} />}
 {tab === 'groups' && <Groups sb={sb} userId={sessionUser.id} />}
 {tab === 'profile' && <Profile name={name} setName={setName} profile={profile} onSettings={() => setSheet('settings')} onAvatar={() => setSheet('avatar')} onSave={async () => { try { await updateProfile(sb, sessionUser.id, { display_name: name, avatar: profile, year_group: yearGroup }); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save profile.'); } }} />}
 {error && <div className="error" style={{ marginTop: 14 }}>{error}<button className="icon-btn" onClick={() => setError('')}><X size={14} /></button></div>}</main><nav className="bottom-nav">{([['home', Users, 'Home'], ['friends', Search, 'Friends'], ['chat', MessageCircle, 'Chat'], ['groups', Users, 'Groups'], ['profile', UserRound, 'Profile']] as const).map(([id, Icon, label]) => <button key={id} className={`nav-item ${tab === id ? 'active' : ''}`} onClick={() => setTab(id)}><Icon size={18} />{label}</button>)}</nav>{sheet && <Sheet type={sheet} close={() => setSheet(null)} mode={mode} ultra={ultra} setUltra={setUltra} profile={profile} setProfile={setProfile} lessons={lessons} sb={sb} userId={sessionUser.id} />}</div>;
}

function Onboarding({ sb, name, setName, email, setEmail, yearGroup, setYearGroup, onEnter, error }: { sb: SupabaseClient; name: string; setName: (v: string) => void; email: string; setEmail: (v: string) => void; yearGroup: number; setYearGroup: (v: number) => void; onEnter: (args: { password: string; accessCode: string; mode: 'signup' | 'login' }) => Promise<boolean> | boolean; error: string }) {
 const [mode, setMode] = useState<'signup' | 'login'>('signup'); const [password, setPassword] = useState(''); const [accessCode, setAccessCode] = useState(''); const [oauthError, setOauthError] = useState('');
 return <div className="onboarding"><div className="onboarding-card"><div className="logo">Bluo<span className="logo-dot" /></div><h1>{mode === 'signup' ? 'Find your people.' : 'Welcome back.'}</h1><p>{mode === 'signup' ? "See who's nearby, find when your friends are free, and never spend a break alone. Bluo starts at Peter Symonds College." : 'Sign in with your PSC student email and Bluo password.'}</p>
 {mode === 'login' && <><label className="control-label">PSC student email</label><input className="input" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@students.psc.ac.uk" inputMode="email" autoComplete="email" /><label className="control-label">Password</label><input className="input" value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" type="password" autoComplete="current-password" /></>}
 {mode === 'signup' && <><label className="control-label">Your real name</label><input className="input" value={name} onChange={e => setName(e.target.value)} placeholder="Your real name" autoComplete="name" /><label className="control-label">Graduation year</label><select className="input" value={yearGroup} onChange={e => setYearGroup(Number(e.target.value))}>{Array.from({ length: 14 }, (_, i) => 2027 + i).map(y => <option value={y} key={y}>{y}</option>)}</select><label className="control-label">PSC launch code</label><input className="input" value={accessCode} onChange={e => setAccessCode(e.target.value)} placeholder="Launch code" autoComplete="off" /><div className="notice" style={{ marginTop: 12 }}>Your PSC Microsoft account verifies that you are using a PSC identity. The launch code controls the initial Bluo rollout.</div></>}
 {(error || oauthError) && <div className="error">{oauthError || error}</div>}
 {mode === 'login' && <button className="primary" style={{ width: '100%', marginTop: 16 }} onClick={() => void onEnter({ password, accessCode, mode })}>Sign in with email & password</button>}
 <PscMicrosoftAuthButton sb={sb} mode={mode} name={name} yearGroup={yearGroup} accessCode={accessCode} onError={setOauthError} />
 <button className="secondary" style={{ width: '100%', marginTop: 8 }} onClick={() => { setMode(mode === 'signup' ? 'login' : 'signup'); setPassword(''); setAccessCode(''); setOauthError(''); }}>{mode === 'signup' ? 'Already have an account? Sign in' : 'New to Bluo? Create an account'}</button><p style={{ fontSize: 11, marginTop: 12 }}>New accounts use your PSC Microsoft account. Email/password is kept only for existing accounts during the transition.</p></div></div>;
}
function PersonRow({ p, onAction }: { p: LivePerson; onAction: () => void }) { return <div className="person"><Avatar config={p.avatar} size={42} /><div className="person-info"><div className="person-name"><span className="status-dot" />{p.name}</div><div className="person-meta">{p.status}</div></div><div className="distance">{p.distance}</div><button className="icon-btn" onClick={onAction} aria-label={`Chat with ${p.name}`}><MessageCircle size={16} /></button></div>; }
function TimetableSummary({ lessons }: { lessons: Lesson[] }) { const now = new Date(); const day = now.getDay() === 0 ? 7 : now.getDay(); const mins = now.getHours() * 60 + now.getMinutes(); const current = lessons.find(l => l.day === day && toMinutes(l.start) <= mins && toMinutes(l.end) > mins); const next = lessons.filter(l => l.day === day && toMinutes(l.start) > mins).sort((a, b) => toMinutes(a.start) - toMinutes(b.start))[0]; return <>{current && <div className="schedule-row"><div className="time">Now</div><div className="lesson"><b>{current.name}</b><span>{current.room || 'Lesson'}</span></div></div>}<div className="schedule-row"><div className="time">Next</div><div className="lesson free"><b>{next ? next.name : 'Free period'}</b><span>{next ? `${next.start} · ${next.room || 'Lesson'}` : 'Add your timetable to see what is next.'}</span></div></div></>; }
function Friends({ people, onFollow }: { people: LivePerson[]; onFollow: (p: LivePerson) => void }) { return <><div className="hero-row"><div><div className="eyebrow">Your connections</div><h1 className="hero-title">Friends</h1></div></div><div className="card side-card">{people.length ? people.map(p => <div className="person" key={p.id}><Avatar config={p.avatar} size={48} /><div className="person-info"><div className="person-name">{p.name}<span style={{ fontWeight: 500, color: '#8b9ab1' }}> · Graduation {p.year || '—'}</span></div><div className="person-meta"><span className="status-dot" style={{ background: p.free ? '#22c76f' : '#aab5c4' }} />{p.status} · Updated {p.updated}</div></div><div className="distance"><button className={p.following ? 'secondary' : 'primary'} onClick={() => onFollow(p)}>{p.mutual ? 'Friends' : p.following ? 'Following' : p.follower ? 'Follow back' : 'Follow'}</button></div></div>) : <p className="person-meta">No other PSC students are visible yet. Share Bluo with your friends to get started.</p>}</div></>; }
function Chat({ people, sb, userId }: { people: LivePerson[]; sb: SupabaseClient | null; userId: string }) { const [selected, setSelected] = useState<LivePerson | null>(people.find(p => p.mutual) || null); const [messages, setMessages] = useState<{ id: string; sender_id: string; body: string; created_at: string }[]>([]); const [text, setText] = useState(''); const load = async () => { if (!sb || !userId || !selected) return; try { setMessages(await getDirectMessages(sb, userId, selected.id) as typeof messages); } catch {} }; useEffect(() => { void load(); const id = window.setInterval(() => void load(), 10000); return () => window.clearInterval(id); }, [selected?.id, userId, sb]); const send = async () => { if (!sb || !selected || !text.trim()) return; try { await sendDirectMessage(sb, userId, selected.id, text); setText(''); await load(); } catch {} }; return <><div className="hero-row"><div><div className="eyebrow">Private messages</div><h1 className="hero-title">Chat</h1></div></div><div className="grid"><section className="card side-card">{people.filter(p => p.mutual || p.follower).map(p => <button key={p.id} className={`person ${selected?.id === p.id ? 'selected-row' : ''}`} onClick={() => setSelected(p)}><Avatar config={p.avatar} size={46} /><div className="person-info"><div className="person-name">{p.name}</div><div className="person-meta">{p.status}</div></div></button>)}{!people.some(p => p.mutual || p.follower) && <p className="person-meta">Become friends with someone to start a chat.</p>}</section><section className="card side-card"><div className="card-title">{selected?.name || 'Select a friend'}</div><div style={{ minHeight: 280, display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', gap: 8, marginTop: 12 }}>{messages.map(m => <div key={m.id} style={{ alignSelf: m.sender_id === userId ? 'flex-end' : 'flex-start', maxWidth: '78%', padding: '9px 12px', borderRadius: 14, background: m.sender_id === userId ? '#e8f2ff' : '#f3f5f8' }}>{m.body}</div>)}</div>{selected && <div style={{ display: 'flex', gap: 8, marginTop: 12 }}><input className="input" value={text} onChange={e => setText(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void send(); }} placeholder="Write a message…" maxLength={4000} /><button className="primary" onClick={() => void send()}>Send</button></div>}</section></div></>; }
function Groups({ sb, userId }: { sb: SupabaseClient | null; userId: string }) { const [groups, setGroups] = useState<{ id: string; name: string; owner_id: string; community: string }[]>([]); const [name, setName] = useState(''); const load = async () => { if (sb) try { setGroups(await getGroups(sb) as typeof groups); } catch {} }; useEffect(() => { void load(); }, [sb]); const make = async () => { if (!sb || !name.trim()) return; try { await createGroup(sb, userId, name); setName(''); await load(); } catch {} }; return <><div className="hero-row"><div><div className="eyebrow">Your communities</div><h1 className="hero-title">Groups</h1></div></div><div className="grid"><section className="card side-card"><div className="card-title">PSC groups</div>{groups.map(g => <div className="person" key={g.id}><div style={{ width: 42, height: 42, borderRadius: 15, background: '#eaf3ff', display: 'grid', placeItems: 'center', color: 'var(--blue)' }}><Users size={19} /></div><div className="person-info"><div className="person-name">{g.name}</div><div className="person-meta">Community group</div></div><ChevronRight size={17} color="#9aa8bc" /></div>)}{!groups.length && <p className="person-meta">No groups yet — create the first one.</p>}</section><section className="card side-card"><div className="card-title">Create a group</div><input className="input" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Year 12 Lunch Crew" maxLength={80} /><button className="primary" style={{ marginTop: 10 }} onClick={() => void make()}><Plus size={16} /> New group</button></section></div></>; }
function Profile({ name, setName, profile, onSettings, onAvatar, onSave }: { name: string; setName: (v: string) => void; profile: AvatarConfig; onSettings: () => void; onAvatar: () => void; onSave: () => void }) { return <><div className="hero-row"><div><div className="eyebrow">Your Bluo</div><h1 className="hero-title">Profile</h1></div><button className="icon-btn" onClick={onSettings} aria-label="Settings"><Settings size={18} /></button></div><div className="card side-card"><div style={{ display: 'flex', gap: 16, alignItems: 'center' }}><Avatar config={profile} size={88} /><div><div className="card-title">{name}</div><div className="person-meta">Your PSC account</div></div></div><button className="secondary" style={{ width: '100%', marginTop: 18 }} onClick={onAvatar}>Customise your Bluo</button><label className="control-label">Display name</label><input className="input" value={name} onChange={e => setName(e.target.value)} onBlur={onSave} maxLength={60} /><button className="primary" style={{ width: '100%', marginTop: 10 }} onClick={onSave}>Save profile</button></div></>; }
function Sheet({ type, close, mode, ultra, setUltra, profile, setProfile, lessons, sb, userId }: { type: 'settings' | 'avatar' | 'timetable' | 'notifications'; close: () => void; mode: DataMode; ultra: boolean; setUltra: (v: boolean) => void; profile: AvatarConfig; setProfile: (v: AvatarConfig) => void; lessons: Lesson[]; sb: SupabaseClient | null; userId: string }) { const [hidden, setHidden] = useState(false); const [dnd, setDnd] = useState(false); const savePrivacy = async (h = hidden, d = dnd) => { if (sb && userId) try { await updateProfile(sb, userId, { dnd: d, visible_to: h ? 'nobody' : 'friends_exact_others_approx' }); } catch {} }; return <><div className="sheet-backdrop" onClick={close} /><div className="sheet"><div className="grabber" />{type === 'settings' && <><h2>Settings</h2><p>Make Bluo work the way you want, even when the college Wi-Fi doesn't.</p><div className="option-grid"><button className="option selected"><b>Adaptive</b><span>Full ↔ Low automatically</span></button><button className={`option ${ultra ? 'selected' : ''}`} onClick={() => setUltra(!ultra)}><b>Ultra low</b><span>{ultra ? 'Included in cycle' : 'Add to adaptive cycle'}</span></button><button className={`option ${hidden ? 'selected' : ''}`} onClick={() => { const next = !hidden; setHidden(next); void savePrivacy(next, dnd); }}><b>{hidden ? 'Location hidden' : 'Location sharing on'}</b><span>Friends exact · others approx.</span></button><button className={`option ${dnd ? 'selected' : ''}`} onClick={() => { const next = !dnd; setDnd(next); void savePrivacy(hidden, next); }}><b>{dnd ? 'Lock In on' : 'Lock In / DND'}</b><span>Quiet notifications and sharing</span></button></div><div className="notice" style={{ marginTop: 14 }}>Current mode: <b>{mode}</b>. Location writes are rate-limited server-side and exact coordinates are never returned to non-mutual users.</div><div className="sheet-actions"><button className="secondary" onClick={close}>Close</button><button className="primary" onClick={async () => { if ('Notification' in window) await Notification.requestPermission(); close(); }}>Enable notifications</button></div></>}{type === 'avatar' && <AvatarEditor config={profile} setConfig={setProfile} close={close} />}{type === 'timetable' && <><h2>Timetable</h2><p>Your timetable turns lessons into availability.</p>{lessons.length ? lessons.map((l, i) => <div className="schedule-row" key={i}><div className="time">D{l.day} {l.start}</div><div className="lesson"><b>{l.name}</b><span>{l.room || 'Lesson'}</span></div></div>) : <div className="notice">No timetable yet. Use the Scan timetable button to import one from a photo.</div>}</>}{type === 'notifications' && <><h2>Notifications</h2><p>Messages, follows and useful availability nudges. Bluo never overrides Lock In.</p><div className="notice">🔔 Browser notification permission can be enabled here.</div></>}</div></>; }
function AvatarEditor({ config, setConfig, close }: { config: AvatarConfig; setConfig: (c: AvatarConfig) => void; close: () => void }) { const colors = ['#F0B98A', '#D99A70', '#8C5A3B', '#6E493A', '#E7C19F', '#B8734E']; const hairs = ['#2A1C17', '#16120F', '#6B3E27', '#A96C3B', '#D9C7B4', '#8C8C96']; const shirts = ['#1B78FF', '#35A66B', '#B35DE6', '#F05A6D', '#F39A3D', '#7D6AF2']; const backgrounds = ['#E8F4FF', '#EEF8F1', '#F6EDFF', '#FFF0F3', '#FFF4E6', '#F0EEFF']; const group = (key: keyof AvatarConfig, values: string[]) => <><label className="control-label">{key}</label><div className="swatches">{values.map(v => <button key={v} className={`swatch ${config[key] === v ? 'selected' : ''}`} style={{ background: v }} onClick={() => setConfig({ ...config, [key]: v })} aria-label={`${key} ${v}`} />)}</div></>; return <><h2>Your Bluo</h2><p>Make a little character that feels like you.</p><div className="avatar-editor"><div className="avatar-preview"><Avatar config={config} size={150} /></div><div>{group('skin', colors)}{group('hair', hairs)}{group('shirt', shirts)}{group('bg', backgrounds)}</div></div><div className="sheet-actions"><button className="secondary" onClick={close}>Done</button></div></>; }
